### PR TITLE
Cosmetic Changes for GQL

### PR DESCRIPTION
**Pull request by jianshen92**
* Remove data type from function names
`generate_schema_dict` -> `parse_schema`
`generate_schema_str` -> `generate_schema`

### CODE REVIEW

**Comment by jianshen92** [comment]
There are multiple names to consider for replacing `_Types`:
```python
allowed_keys = ["_Interfaces", "_Types", "_Scalars", "_Enums", "_Inputs"]
schema_dict = select_keys(schema_dict, *allowed_keys)
dispatch = {
    "_Interfaces":  parse_interfaces_or_types["interface"],
    "_Types":       parse_interfaces_or_types["type"],
    "_Scalars":     parse_scalars,
    "_Enums":       parse_enums,
    "_Inputs":      parse_inputs,
}
```

**Review by zeyadkhaled — COMMENTED** [review]
The one comment I have both of these functions have the suffix `schema` but one works on a string and the other on a dict. So not sure if this is clear enough for usage by users. @UlfBissbort what do you think?

**Comment by zeyadkhaled** [comment]
> There are multiple names to consider for replacing `_Types`:
> 
> ```python
> allowed_keys = ["_Interfaces", "_Types", "_Scalars", "_Enums", "_Inputs"]
> schema_dict = select_keys(schema_dict, *allowed_keys)
> dispatch = {
>     "_Interfaces":  parse_interfaces_or_types["interface"],
>     "_Types":       parse_interfaces_or_types["type"],
>     "_Scalars":     parse_scalars,
>     "_Enums":       parse_enums,
>     "_Inputs":      parse_inputs,
> }
> ```

Yeah we can just change the `_` prefix with `GraphQL` for all of them, I think.

**Comment by jianshen92** [comment]
> The one comment I have both of these functions have the suffix `schema` but one works on a string and the other on a dict. So not sure if this is clear enough for usage by users. @UlfBissbort what do you think?

My thinking is that, the "schema string" is commonly known as THE schema by most people. so `parse_schema` is parsing THE schema while `generate_schema` is generating THE schema

**Pull request merged**
